# Generated by Django 5.1.6 on 2025-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metric', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
